version: '3'

services:
  fastapi_app_0:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - CONTAINERNAME=fastapi_app_0
      
  fastapi_app_1:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - app-network
    environment:
      - CONTAINERNAME=fastapi_app_1

  fastapi_app_2:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    networks:
      - app-network
    environment:
      - CONTAINERNAME=fastapi_app_2

  fastapi_app_3:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    networks:
      - app-network
    environment:
      - CONTAINERNAME=fastapi_app_3

  fastapi_app_4:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    networks:
      - app-network
    environment:
      - CONTAINERNAME=fastapi_app_4

networks:
  app-network:
    driver: bridge
