version: '3'
services:
  node1:
    build: .
    ports:
      - "5001:5000"
    networks:
      - blockchain_network

  node2:
    build: .
    ports:
      - "5002:5000"
    networks:
      - blockchain_network

  node3:
    build: .
    ports:
      - "5003:5000"
    networks:
      - blockchain_network

  node4:
    build: .
    ports:
      - "5004:5000"
    networks:
      - blockchain_network

networks:
  blockchain_network:
    driver: bridge
